### ISSUE TITLE
エンダーチェストメニューを同時に表示できない

### ISSUE THREAD

**Issue by NePonpon** [NePonpon/pvp-with-everyone#6]
## 概要
1人がメニューを表示しているときに、別の人がエンダーチェストを開いても、メニューが表示されない。

## 詳細
[`control:open-ender_chest`](https://github.com/NePonpon/pvp-with-everyone/blob/master/data/control/functions/open-ender_chest.mcfunction)が実行されない。

## 応急処置での解決
`control:tick`のscheduleをclearすると開けるようになった。

## 解決案
`control:tick`のloopは1tickである。  
これを2tickのloopに変更してみる。

**Comment by NePonpon** [comment]
[`bug/no_show_menu`](https://github.com/NePonpon/pvp-with-everyone/tree/bug/no_show_menu)ブランチの[`tick処理をを2tickloopに変更`](https://github.com/NePonpon/pvp-with-everyone/commit/07c74535b643bbf27fe1174d25189099fe3fbfa4)で検証。  
鯖での反映後、複数人にメニューが表示できるようにできたことを確認。

**Comment by Teddyson12** [comment]
> [`bug/no_show_menu`](https://github.com/NePonpon/pvp-with-everyone/tree/bug/no_show_menu)ブランチの[`tick処理をを2tickloopに変更`](https://github.com/NePonpon/pvp-with-everyone/commit/07c74535b643bbf27fe1174d25189099fe3fbfa4)で検証。 鯖での反映後、複数人にメニューが表示できるようにできたことを確認。
