### ISSUE TITLE
メニュー再更新時、他人のメニューを表示する

### ISSUE THREAD

**Issue by NePonpon** [NePonpon/pvp-with-everyone#7]
## 概要
メニューを再更新するときに、他人が表示中のメニューを表示してしまう。

## 詳細
再更新するメニューを格納しているstorage`control:menu ShowMenu`を複数人で使いまわすため、他人のページを参照してしまう。

## 再現方法

1. 1人がメニューを表示する。
2. もう1人が別のメニューを表示する。
3. 最初の1人がメニューを再更新する。
4. 別のメニューを開いていた人のメニューが表示される。

## 問題点
クリエイティブ用のゲーム設定画面をプレイヤーのメニューに表示することができる。

## 解決法
OhMyDatを使用し、それぞれが`ShowMenu`を保存し、それを参照して再更新する。

**Comment by Teddyson12** [comment]
Please send back the Money thanks I made a mistake
Duplicate of #

**Comment by Teddyson12** [comment]
Please send it's back I made a mistake

**Comment by Teddyson12** [comment]
> 

https://github.com/NePonpon/pvp-with-everyone/issues/7#issue-1070182498

**Comment by NePonpon** [comment]
#8 で修正
